import { createHmac } from "node:crypto";
import { requireEnv } from "./env";

/** Per-extension SIP password, derived — never stored in the database. */
export function sipPassword(extension: string): string {
  return createHmac("sha256", requireEnv("SIP_EXTENSION_SECRET")).update(`ext:${extension}`).digest("base64url").slice(0, 32);
}

/** coturn use-auth-secret ephemeral credentials (TURN REST API). */
export function turnCredentials(extension: string, ttl = 3600) {
  const secret = process.env.TURN_SECRET;
  const urls = (process.env.TURN_URLS || "").split(",").map((s) => s.trim()).filter(Boolean);
  if (!secret || urls.length === 0) return null;
  const username = `${Math.floor(Date.now() / 1000) + ttl}:${extension}`;
  const credential = createHmac("sha1", secret).update(username).digest("base64");
  return { urls, username, credential };
}

export function renderUsersPjsip(rows: { extension: string; enabled: boolean }[]): string {
  const out = ["; GENERATED by PrivateCall — WebRTC extensions. Do not edit by hand."];
  for (const r of rows) {
    if (!r.enabled || !/^\d{3,8}$/.test(r.extension)) continue;
    const e = r.extension;
    out.push(`
[${e}](webrtc-endpoint)
auth=${e}
aors=${e}

[${e}](webrtc-auth)
username=${e}
password=${sipPassword(e)}

[${e}](webrtc-aor)`);
  }
  return out.join("\n") + "\n";
}
