// Converts the authoritative pack metadata into typed TS modules.
// Run: npm run build:data
import fs from 'node:fs';

const P = 'public/';
const csv = fs.readFileSync(P + 'audio/analysis/lip_sync_30fps.csv', 'utf8').replace(/^﻿/, '');
const rows = csv.trim().split(/\r?\n/).slice(1).map((l) => {
  const [frame, time, speaker, line, level, mouth] = l.split(',');
  return {frame: +frame, speaker, line, level: +level, mouth: +mouth};
});
rows.forEach((r, i) => { if (r.frame !== i) throw new Error('non-contiguous frame ' + i); });

const SPEAKERS = ['none', 'fatima', 'ghozlan', 'dr_heba', 'narrator'];
const speaker = rows.map((r) => SPEAKERS.indexOf(r.speaker));
if (speaker.includes(-1)) throw new Error('unknown speaker');

// Smoothing (timing-preserving): a state that lasts a single frame and differs
// from both neighbours is replaced by the lower neighbour state. Speech onsets
// and offsets are untouched because a mouth is only ever opened on frames the
// CSV marks as speech.
const raw = rows.map((r) => r.mouth);
const mouth = raw.slice();
let smoothed = 0;
for (let i = 1; i < raw.length - 1; i++) {
  if (raw[i] !== raw[i - 1] && raw[i] !== raw[i + 1] && rows[i].speaker !== 'none') {
    mouth[i] = Math.min(raw[i - 1], raw[i + 1]);
    smoothed++;
  }
}
for (let i = 0; i < rows.length; i++) if (rows[i].speaker === 'none') mouth[i] = 0;

const transcript = JSON.parse(fs.readFileSync(P + 'data/transcript.json', 'utf8'));
const scenePlan = JSON.parse(fs.readFileSync(P + 'data/scene_plan.json', 'utf8'));
const config = JSON.parse(fs.readFileSync(P + 'data/project_config.json', 'utf8'));
const anchors = JSON.parse(fs.readFileSync(P + 'data/character_anchors.json', 'utf8'));

const header = '// AUTO-GENERATED by scripts/build-data.mjs from the asset pack. Do not edit.\n';
fs.writeFileSync('src/data/lipSync.generated.ts', header +
  `export const SPEAKER_NAMES = ${JSON.stringify(SPEAKERS)} as const;\n` +
  `export const RAW_MOUTH = '${raw.join('')}';\n` +
  `export const MOUTH = '${mouth.join('')}';\n` +
  `export const SPEAKER = '${speaker.join('')}';\n` +
  `export const SMOOTHED_FRAMES = ${smoothed};\n`);
fs.writeFileSync('src/data/pack.generated.ts', header +
  `export const PROJECT_CONFIG = ${JSON.stringify(config, null, 2)} as const;\n` +
  `export const SCENE_PLAN = ${JSON.stringify(scenePlan, null, 2)} as const;\n` +
  `export const TRANSCRIPT = ${JSON.stringify(transcript, null, 2)} as const;\n` +
  `export const ANCHORS = ${JSON.stringify(anchors, null, 2)} as const;\n`);
console.log(`frames=${rows.length} smoothedBlips=${smoothed}`);
