import type { DialFormat, ProviderAdapter, ProviderConfig } from "./types";
import { localphone } from "./localphone";
import { telnyx } from "./telnyx";
import { genericSip } from "./generic-sip";

export type { ProviderConfig, ProviderAdapter } from "./types";

export const ADAPTERS: Record<string, ProviderAdapter> = {
  [localphone.id]: localphone,
  [telnyx.id]: telnyx,
  [genericSip.id]: genericSip,
};

export const TRUNK_NAME = "provider-trunk";

type Env = Record<string, string | undefined>;

export function loadProviderConfig(env: Env = process.env): ProviderConfig | null {
  const id = (env.SIP_PROVIDER || "").trim().toLowerCase();
  if (!id) return null;
  const d = ADAPTERS[id]?.defaults ?? {};
  const missingRequired = (ADAPTERS[id]?.requiredEnv ?? []).filter((k) => !env[k]);
  return {
    provider: id,
    host: env.SIP_HOST || d.host || "",
    port: Number(env.SIP_PORT || d.port || 5060),
    transport: (env.SIP_TRANSPORT || d.transport || "udp") as ProviderConfig["transport"],
    username: env.SIP_USERNAME || "",
    password: env.SIP_PASSWORD || "",
    fromNumber: env.SIP_FROM_NUMBER || "",
    privacyEnabled: (env.SIP_PRIVACY_ENABLED ?? "true") !== "false",
    dialFormat: (env.SIP_DIAL_FORMAT || d.dialFormat || "e164") as DialFormat,
    dialPrefix: env.SIP_DIAL_PREFIX || "",
    register: env.SIP_REGISTER ? env.SIP_REGISTER !== "false" : d.register ?? true,
    missingRequired,
  };
}

export function validateProviderConfig(cfg: ProviderConfig | null): { configured: boolean; errors: string[] } {
  if (!cfg) return { configured: false, errors: ["SIP_PROVIDER not set"] };
  const e: string[] = [];
  for (const k of cfg.missingRequired ?? []) e.push(`${k} must be set explicitly for ${cfg.provider}`);
  if (!ADAPTERS[cfg.provider]) e.push(`Unknown SIP_PROVIDER "${cfg.provider}"`);
  if (!cfg.host || !/^[a-zA-Z0-9.-]+$/.test(cfg.host)) e.push("SIP_HOST missing or invalid");
  if (!Number.isInteger(cfg.port) || cfg.port < 1 || cfg.port > 65535) e.push("SIP_PORT invalid");
  if (!["udp", "tcp", "tls"].includes(cfg.transport)) e.push("SIP_TRANSPORT invalid");
  if (!cfg.username) e.push("SIP_USERNAME missing");
  if (!cfg.password) e.push("SIP_PASSWORD missing");
  if (!/^\+?\d{6,15}$/.test(cfg.fromNumber)) e.push("SIP_FROM_NUMBER missing or not E.164");
  if (!["e164", "digits", "intl00"].includes(cfg.dialFormat ?? "e164")) e.push("SIP_DIAL_FORMAT invalid");
  if (cfg.dialPrefix && !/^[\d*#]{1,8}$/.test(cfg.dialPrefix)) e.push("SIP_DIAL_PREFIX invalid");
  // Values end up in pjsip.conf: forbid config injection.
  for (const [k, v] of Object.entries(cfg)) if (typeof v === "string" && /[\r\n;\[\]]/.test(v)) e.push(`${k} contains forbidden characters`);
  return { configured: e.length === 0, errors: e };
}

/** The number string sent in the Request-URI to the trunk. */
export function formatDialNumber(e164: string, cfg: Pick<ProviderConfig, "dialFormat" | "dialPrefix">): string {
  const digits = e164.replace(/^\+/, "");
  const body = cfg.dialFormat === "digits" ? digits : cfg.dialFormat === "intl00" ? `00${digits}` : `+${digits}`;
  return `${cfg.dialPrefix || ""}${body}`;
}

/** Renders the provider trunk for Asterisk. Endpoint name never changes between providers. */
export function renderTrunkPjsip(cfg: ProviderConfig): string {
  const hostport = `${cfg.host}:${cfg.port}`;
  const t = `transport-${cfg.transport}`;
  return `; GENERATED by PrivateCall for provider "${cfg.provider}" — do not edit by hand.
[${TRUNK_NAME}-auth]
type=auth
auth_type=userpass
username=${cfg.username}
password=${cfg.password}

[${TRUNK_NAME}]
type=aor
contact=sip:${hostport}
qualify_frequency=60

[${TRUNK_NAME}]
type=endpoint
transport=${t}
context=from-provider
disallow=all
allow=alaw,ulaw
outbound_auth=${TRUNK_NAME}-auth
aors=${TRUNK_NAME}
from_user=${cfg.username}
from_domain=${cfg.host}
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
; CLIR / privacy (RFC 3325): real account identity in PAI + "Privacy: id",
; From becomes Anonymous when the dialplan sets CALLERID(pres)=prohib.
send_pai=yes
send_rpid=no
trust_id_outbound=yes

[${TRUNK_NAME}]
type=identify
endpoint=${TRUNK_NAME}
match=${cfg.host}
${
  cfg.register
    ? `
[${TRUNK_NAME}-reg]
type=registration
transport=${t}
outbound_auth=${TRUNK_NAME}-auth
server_uri=sip:${hostport}
client_uri=sip:${cfg.username}@${hostport}
retry_interval=60
`
    : ""
}`;
}
