[modules]
autoload=yes
; Required: res_pjsip*, res_http_websocket, res_pjsip_transport_websocket, res_srtp,
; res_rtp_asterisk, func_curl, res_curl, app_dial (opus optional)
noload => chan_sip.so
noload => chan_iax2.so
noload => chan_skinny.so
noload => chan_mgcp.so
noload => chan_unistim.so
noload => pbx_ael.so
noload => pbx_lua.so
noload => res_phoneprov.so
noload => cdr_sqlite3_custom.so
noload => cel_sqlite3_custom.so
