// AUTO-GENERATED by scripts/build-data.mjs from the asset pack. Do not edit.
export const PROJECT_CONFIG = {
  "title": "Egyptian Family Planning Healthcare Explainer",
  "resolution": [
    1080,
    1920
  ],
  "fps": 30,
  "duration_s": 67.47425,
  "total_frames": 2025,
  "audio_master": "audio/master/master_voice_48k_pcm24.wav",
  "audio_is_immutable": true,
  "style": "flat 2D pastel healthcare illustration",
  "language": "Egyptian Arabic"
} as const;
export const SCENE_PLAN = [
  {
    "scene": 1,
    "name": "Home / Hook",
    "start": 0,
    "end": 8.3,
    "reference": "scene_references/01_home_reference.png",
    "background": "backgrounds/home_night_1080x1920.png",
    "speakers": [
      "fatima"
    ],
    "notes": "Fatima beside crying baby; slow push-in; worried/tired."
  },
  {
    "scene": 2,
    "name": "Clinic / Nurse + Fatima",
    "start": 8.3,
    "end": 17.48,
    "reference": "scene_references/02_clinic_support_reference.png",
    "background": "backgrounds/clinic_1080x1920.png",
    "speakers": [
      "ghozlan",
      "fatima"
    ],
    "notes": "Ghozlan comforting hand; then Fatima asks what to do."
  },
  {
    "scene": 3,
    "name": "Doctor enters / surprise",
    "start": 17.48,
    "end": 25.4,
    "reference": "scene_references/03_clinic_doctor_reference.png",
    "background": "backgrounds/clinic_1080x1920.png",
    "speakers": [
      "dr_heba",
      "fatima"
    ],
    "notes": "Dr Heba explains pregnancy before cycle; Fatima reacts."
  },
  {
    "scene": 4,
    "name": "Methods explainer",
    "start": 25.4,
    "end": 39.96,
    "reference": "scene_references/04_methods_icons_reference.png",
    "background": "backgrounds/clinic_1080x1920.png",
    "speakers": [
      "dr_heba"
    ],
    "notes": "Icons appear sequentially: IUD, pills, injection, implant, breastfeeding heart."
  },
  {
    "scene": 5,
    "name": "Choice + spacing",
    "start": 39.96,
    "end": 52.25,
    "reference": "scene_references/05_family_vignette_reference.png",
    "background": "backgrounds/clinic_1080x1920.png",
    "speakers": [
      "ghozlan",
      "fatima",
      "dr_heba"
    ],
    "notes": "Supportive talk; Fatima relief; family spacing vignette."
  },
  {
    "scene": 6,
    "name": "Health unit exterior",
    "start": 52.25,
    "end": 57.51,
    "reference": "scene_references/06_exterior_reference.png",
    "background": "backgrounds/health_unit_exterior_1080x1920.png",
    "speakers": [
      "ghozlan"
    ],
    "notes": "All three at entrance; Ghozlan addresses viewer."
  },
  {
    "scene": 7,
    "name": "End card",
    "start": 57.51,
    "end": 67.47425,
    "reference": "scene_references/07_end_card_reference.png",
    "background": "backgrounds/end_card_mint_1080x1920.png",
    "speakers": [
      "narrator"
    ],
    "notes": "No visible speaker; keep center empty for logos."
  }
] as const;
export const TRANSCRIPT = [
  {
    "id": "L01",
    "speaker": "fatima",
    "start": 0.976,
    "end": 5.164,
    "text": "ابني الأولاني لسه ما كملش سنة… وأنا دلوقتي في الشهر التاسع.",
    "emotion": "تعب وإرهاق وقلق"
  },
  {
    "id": "L02",
    "speaker": "fatima",
    "start": 5.574,
    "end": 8.128,
    "text": "كنت فاكرة إن الرضاعة بتحمي… ومستنية الدورة ترجع الأول.",
    "emotion": "حيرة وندم خفيف"
  },
  {
    "id": "L03",
    "speaker": "ghozlan",
    "start": 8.466,
    "end": 14.592,
    "text": "وده بالظبط اللي بيحصل مع ستات كتير يا حبيبتي… بس المرة دي، هنفكر بدري.",
    "emotion": "حنان وطمأنة"
  },
  {
    "id": "L04",
    "speaker": "fatima",
    "start": 14.834,
    "end": 17.115,
    "text": "طب أعمل إيه؟… أنا خايفة أغلط تاني.",
    "emotion": "خوف وتردد"
  },
  {
    "id": "L05",
    "speaker": "dr_heba",
    "start": 17.487,
    "end": 23.461,
    "text": "اسمعي المعلومة دي كويس… الحمل ممكن ييجي قبل ما الدورة ترجع، وإنتي مش واخدة بالك.",
    "emotion": "ثقة وطمأنة مهنية"
  },
  {
    "id": "L06",
    "speaker": "fatima",
    "start": 23.716,
    "end": 25.134,
    "text": "قبل الدورة؟!",
    "emotion": "صدمة واستغراب"
  },
  {
    "id": "L07",
    "speaker": "dr_heba",
    "start": 25.408,
    "end": 39.663,
    "text": "أيوه… عشان كده الوسيلة تتحدد من دلوقتي. في اللولب، وممكن يتركّب بعد الولادة على طول أو بعد الأربعين… وفي حبوب الرضاعة، والحقنة، والكبسولة تحت الجلد… وكلهم آمنين على الرضاعة.",
    "emotion": "شرح هادئ وواثق"
  },
  {
    "id": "L08",
    "speaker": "ghozlan",
    "start": 39.964,
    "end": 43.954,
    "text": "وإنتي اللي تختاري معانا… حسب صحتك وظروفك.",
    "emotion": "دعم وتمكين"
  },
  {
    "id": "L09",
    "speaker": "fatima",
    "start": 43.954,
    "end": 47.159,
    "text": "يعني المرة دي… أنا اللي هقرر إمتى؟",
    "emotion": "ارتياح وأمل"
  },
  {
    "id": "L10",
    "speaker": "dr_heba",
    "start": 47.697,
    "end": 52.036,
    "text": "بالظبط… تلات سنين بين كل ولادة والتانية… عشان صحتك… وصحة ولادك.",
    "emotion": "طمأنة وفخر"
  },
  {
    "id": "L11",
    "speaker": "ghozlan",
    "start": 52.253,
    "end": 57.222,
    "text": "المشورة متاحة في أقرب وحدة صحية ليكي… ووسيلتك تبدأ من مشورتك.",
    "emotion": "دعوة دافئة وواضحة"
  },
  {
    "id": "L12",
    "speaker": "narrator",
    "start": 57.512,
    "end": 67.234,
    "text": "حملة تنمية الأسرة المصرية. برعاية وزارة الصحة والسكان، مديرية الشؤون الصحية بالجيزة. مع تحيات المنسق الإعلامي، سهير غانم.",
    "emotion": "رسمي دافئ وواثق"
  }
] as const;
export const ANCHORS = {
  "fatima": {
    "file": "characters/clean/fatima.png",
    "size_px": [
      319,
      1148
    ],
    "mouth_anchor_px": [
      155.4,
      122.7
    ],
    "mouth_anchor_normalized": [
      0.4872,
      0.1069
    ],
    "skin_rgb": [
      246,
      175,
      139
    ]
  },
  "ghozlan": {
    "file": "characters/clean/ghozlan.png",
    "size_px": [
      350,
      1145
    ],
    "mouth_anchor_px": [
      178,
      123.1
    ],
    "mouth_anchor_normalized": [
      0.5085,
      0.1075
    ],
    "skin_rgb": [
      234,
      157,
      120
    ]
  },
  "dr_heba": {
    "file": "characters/clean/dr_heba.png",
    "size_px": [
      343,
      1168
    ],
    "mouth_anchor_px": [
      165.7,
      138.8
    ],
    "mouth_anchor_normalized": [
      0.4832,
      0.1188
    ],
    "skin_rgb": [
      242,
      168,
      130
    ]
  }
} as const;
